import { useEffect, useRef, useState } from 'react';
import { Brush, Download, Eraser, Hand, Minus, MousePointer2, Plus, Redo2, RotateCcw, Sparkles, Undo2, Upload, ZoomIn, ZoomOut } from 'lucide-react';
import { MobileSamOnnxModel } from '../../lib/onnx/model';
import { subtractMasksFast, unionMasksFast } from '../../lib/wasm';
import type { BoundingBox, ImageEmbedding, PromptPoint, Tool } from '../../types/editor';

const model = new MobileSamOnnxModel();
type Hist = { mask: Uint8Array; alpha: Uint8Array };

export function ImageEditor() {
  const canvasRef = useRef<HTMLCanvasElement>(null), hostRef = useRef<HTMLDivElement>(null);
  const bitmap = useRef<ImageBitmap|null>(null), original = useRef<ImageData|null>(null), current = useRef<ImageData|null>(null), embedding = useRef<ImageEmbedding|null>(null);
  const maskRef = useRef<Uint8Array|null>(null), dragStart = useRef<{x:number;y:number}|null>(null), boxRef = useRef<BoundingBox|null>(null), panStart = useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
  const history = useRef<Hist[]>([]), future = useRef<Hist[]>([]);
  const [tool,setTool]=useState<Tool>('smart'), [zoom,setZoom]=useState(1), [offset,setOffset]=useState({x:0,y:0}), [version,setVersion]=useState(0);
  const [status,setStatus]=useState('Loading AI model...'), [error,setError]=useState<string|null>(null), [threshold,setThreshold]=useState(128), [brushSize,setBrushSize]=useState(28), [feather,setFeather]=useState(0);

  useEffect(()=>{ model.load().then(()=>setStatus('AI ready')).catch(e=>{setStatus('AI unavailable');setError(`Model loading failed: ${e.message}`)}); },[]);

  const draw=()=>{
    const c=canvasRef.current,h=hostRef.current,img=current.current;if(!c||!h)return;
    const dpr=devicePixelRatio||1;c.width=Math.round(h.clientWidth*dpr);c.height=Math.round(h.clientHeight*dpr);c.style.width=`${h.clientWidth}px`;c.style.height=`${h.clientHeight}px`;
    const ctx=c.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,h.clientWidth,h.clientHeight);if(!img)return;
    const temp=document.createElement('canvas');temp.width=img.width;temp.height=img.height;temp.getContext('2d')!.putImageData(img,0,0);
    ctx.save();ctx.translate(offset.x,offset.y);ctx.scale(zoom,zoom);ctx.drawImage(temp,0,0);
    const m=maskRef.current;if(m){const ov=document.createElement('canvas');ov.width=img.width;ov.height=img.height;const oi=ov.getContext('2d')!.createImageData(img.width,img.height);for(let i=0;i<m.length;i++){if(m[i]>=threshold){oi.data[i*4]=59;oi.data[i*4+1]=130;oi.data[i*4+2]=246;oi.data[i*4+3]=100;}}ov.getContext('2d')!.putImageData(oi,0,0);ctx.drawImage(ov,0,0);}
    if(boxRef.current){const b=boxRef.current;ctx.strokeStyle='#60a5fa';ctx.lineWidth=2/zoom;ctx.setLineDash([6/zoom,4/zoom]);ctx.strokeRect(b.x1,b.y1,b.x2-b.x1,b.y2-b.y1);}ctx.restore();
  };
  useEffect(draw,[zoom,offset,version,threshold]);
  useEffect(()=>{const f=()=>draw();window.addEventListener('resize',f);return()=>window.removeEventListener('resize',f)},[zoom,offset,version,threshold]);

  const fit=(w:number,h:number)=>{const host=hostRef.current;if(!host)return;const z=Math.min((host.clientWidth-80)/w,(host.clientHeight-80)/h,1);setZoom(z);setOffset({x:(host.clientWidth-w*z)/2,y:(host.clientHeight-h*z)/2});};
  const loadImage=async(file:File)=>{setError(null);if(file.size>50*1024*1024){setError('Image is too large (50 MB maximum).');return;}const bmp=await createImageBitmap(file);bitmap.current=bmp;const c=new OffscreenCanvas(bmp.width,bmp.height),ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(bmp,0,0);const data=ctx.getImageData(0,0,bmp.width,bmp.height);original.current=new ImageData(new Uint8ClampedArray(data.data),bmp.width,bmp.height);current.current=data;maskRef.current=new Uint8Array(bmp.width*bmp.height);history.current=[];future.current=[];fit(bmp.width,bmp.height);setVersion(v=>v+1);setStatus('Analyzing image...');try{embedding.current=await model.encodeImage(bmp);setStatus('Ready — Smart Select an object');}catch(e:any){setError(`Image analysis failed: ${e.message}`);setStatus('AI unavailable');}};
  const point=(e:React.PointerEvent)=>{const r=canvasRef.current!.getBoundingClientRect();return{x:(e.clientX-r.left-offset.x)/zoom,y:(e.clientY-r.top-offset.y)/zoom};};
  const inImage=(p:{x:number;y:number})=>!!current.current&&p.x>=0&&p.y>=0&&p.x<current.current.width&&p.y<current.current.height;
  const snapshot=()=>{const img=current.current,m=maskRef.current;if(!img||!m)return;const a=new Uint8Array(m.length);for(let i=0;i<a.length;i++)a[i]=img.data[i*4+3];history.current.push({mask:new Uint8Array(m),alpha:a});if(history.current.length>30)history.current.shift();future.current=[];};
  const restoreHist=(s:Hist)=>{const img=current.current;if(!img)return;maskRef.current=new Uint8Array(s.mask);for(let i=0;i<s.alpha.length;i++)img.data[i*4+3]=s.alpha[i];setVersion(v=>v+1);};
  const undo=()=>{const prev=history.current.pop(),img=current.current,m=maskRef.current;if(!prev||!img||!m)return;const a=new Uint8Array(m.length);for(let i=0;i<a.length;i++)a[i]=img.data[i*4+3];future.current.push({mask:new Uint8Array(m),alpha:a});restoreHist(prev)};
  const redo=()=>{const nxt=future.current.pop(),img=current.current,m=maskRef.current;if(!nxt||!img||!m)return;const a=new Uint8Array(m.length);for(let i=0;i<a.length;i++)a[i]=img.data[i*4+3];history.current.push({mask:new Uint8Array(m),alpha:a});restoreHist(nxt)};
  const predict=async(points?:PromptPoint[],box?:BoundingBox,mode:'replace'|'add'|'subtract'='replace')=>{if(!embedding.current)return;setStatus('Selecting...');try{const res=await model.predictMask({embedding:embedding.current,points,box});snapshot();if(mode==='add')maskRef.current=await unionMasksFast(maskRef.current!,res.mask);else if(mode==='subtract')maskRef.current=await subtractMasksFast(maskRef.current!,res.mask);else maskRef.current=res.mask;setStatus(`Selected · confidence ${(res.score*100).toFixed(0)}%`);setVersion(v=>v+1)}catch(e:any){setError(`Selection failed: ${e.message}`);setStatus('Ready')}};
  const paint=(p:{x:number;y:number},erase:boolean)=>{const m=maskRef.current,img=current.current;if(!m||!img)return;const rad=brushSize/2;for(let y=Math.max(0,Math.floor(p.y-rad));y<Math.min(img.height,Math.ceil(p.y+rad));y++)for(let x=Math.max(0,Math.floor(p.x-rad));x<Math.min(img.width,Math.ceil(p.x+rad));x++)if((x-p.x)**2+(y-p.y)**2<=rad**2)m[y*img.width+x]=erase?0:255;setVersion(v=>v+1)};
  const down=(e:React.PointerEvent)=>{canvasRef.current!.setPointerCapture(e.pointerId);const p=point(e);if(tool==='move'){panStart.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};return;}if(!inImage(p))return;snapshot();dragStart.current=p;if(tool==='brush'||tool==='eraser')paint(p,tool==='eraser');};
  const move=(e:React.PointerEvent)=>{if(panStart.current){setOffset({x:panStart.current.ox+e.clientX-panStart.current.x,y:panStart.current.oy+e.clientY-panStart.current.y});return;}if(!dragStart.current)return;const p=point(e);if(tool==='brush'||tool==='eraser'){paint(p,tool==='eraser');return;}boxRef.current={x1:dragStart.current.x,y1:dragStart.current.y,x2:p.x,y2:p.y};setVersion(v=>v+1);};
  const up=(e:React.PointerEvent)=>{if(panStart.current){panStart.current=null;return;}const start=dragStart.current;if(!start)return;const p=point(e),dist=Math.hypot(p.x-start.x,p.y-start.y);dragStart.current=null;if(tool==='brush'||tool==='eraser')return;const mode=tool==='add'||e.shiftKey?'add':tool==='subtract'?'subtract':'replace';if(dist>6){const b={x1:Math.min(start.x,p.x),y1:Math.min(start.y,p.y),x2:Math.max(start.x,p.x),y2:Math.max(start.y,p.y)};boxRef.current=null;predict(undefined,b,mode);}else{boxRef.current=null;predict([{x:p.x,y:p.y,label:e.altKey?0:1}],undefined,mode);}setVersion(v=>v+1);};
  const apply=(restore=false)=>{const img=current.current,orig=original.current,m=maskRef.current;if(!img||!orig||!m)return;snapshot();for(let i=0;i<m.length;i++)if(m[i]>=threshold)img.data[i*4+3]=restore?orig.data[i*4+3]:0;setVersion(v=>v+1)};
  const clear=()=>{if(!maskRef.current)return;snapshot();maskRef.current.fill(0);setVersion(v=>v+1)};
  const reset=()=>{if(!original.current)return;snapshot();current.current=new ImageData(new Uint8ClampedArray(original.current.data),original.current.width,original.current.height);maskRef.current?.fill(0);setVersion(v=>v+1)};
  const download=()=>{const img=current.current;if(!img)return;const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d')!.putImageData(img,0,0);c.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='removed-background.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')};
  const tools:[Tool,string,any][]=[['move','Move',Hand],['smart','Smart Select',Sparkles],['add','Add Selection',Plus],['subtract','Subtract',Minus],['brush','Brush',Brush],['eraser','Eraser',Eraser]];
  return <div className="flex h-full flex-col bg-neutral-950 text-neutral-100">
    <header className="flex h-14 shrink-0 items-center gap-2 border-b border-white/10 px-3"><div className="mr-3 flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-blue-600"><Sparkles size={17}/></span>Remove BG</div><label className="flex cursor-pointer items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm font-medium text-neutral-900"><Upload size={16}/>Upload<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&loadImage(e.target.files[0])}/></label><span className="mx-1 h-6 w-px bg-white/10"/><button onClick={undo} className="p-2" title="Undo"><Undo2 size={17}/></button><button onClick={redo} className="p-2" title="Redo"><Redo2 size={17}/></button><button onClick={reset} className="p-2" title="Reset"><RotateCcw size={17}/></button><div className="ml-auto flex items-center gap-2 text-xs text-neutral-400"><span className="hidden sm:inline">Your images stay on your device.</span><span className="rounded-full bg-white/5 px-2 py-1">{status}</span></div></header>
    <main className="flex min-h-0 flex-1">
      <aside className="hidden w-20 shrink-0 flex-col items-center gap-2 border-r border-white/10 py-3 md:flex">{tools.map(([id,label,Icon])=><button key={id} onClick={()=>setTool(id)} title={label} className={`grid size-11 place-items-center rounded-xl ${tool===id?'bg-blue-600':'bg-white/5 hover:bg-white/10'}`}><Icon size={19}/></button>)}</aside>
      <section ref={hostRef} className="checkerboard relative min-w-0 flex-1 overflow-hidden"><canvas ref={canvasRef} className="absolute inset-0 touch-none" onPointerDown={down} onPointerMove={move} onPointerUp={up}/>{!current.current&&<div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="rounded-2xl border border-white/10 bg-neutral-900/90 p-8 text-center shadow-2xl"><MousePointer2 className="mx-auto mb-3 text-blue-400"/><h2 className="text-lg font-semibold">Upload an image to start</h2><p className="mt-1 text-sm text-neutral-400">Smart selection runs locally in your browser.</p></div></div>}{error&&<div className="absolute left-1/2 top-4 -translate-x-1/2 rounded-lg border border-red-500/30 bg-red-950/90 px-4 py-2 text-sm text-red-200">{error}</div>}<div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-1 rounded-xl border border-white/10 bg-neutral-900/90 p-1 shadow-xl"><button className="p-2" onClick={()=>setZoom(z=>Math.max(.05,z/1.2))}><ZoomOut size={17}/></button><span className="w-14 py-2 text-center text-xs">{Math.round(zoom*100)}%</span><button className="p-2" onClick={()=>setZoom(z=>Math.min(8,z*1.2))}><ZoomIn size={17}/></button>{current.current&&<button className="rounded-lg px-2 text-xs hover:bg-white/10" onClick={()=>fit(current.current!.width,current.current!.height)}>Fit</button>}</div></section>
      <aside className="hidden w-72 shrink-0 border-l border-white/10 p-4 lg:block"><h3 className="font-semibold">Selection</h3><p className="mt-1 text-xs text-neutral-400">Click = positive · Alt-click = negative · drag = box</p><label className="mt-5 block text-xs text-neutral-300">Threshold <span className="float-right">{threshold}</span><input className="mt-2 w-full accent-blue-500" type="range" min="1" max="254" value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label><label className="mt-4 block text-xs text-neutral-300">Feather <span className="float-right">{feather}px</span><input className="mt-2 w-full accent-blue-500" type="range" min="0" max="32" value={feather} onChange={e=>setFeather(+e.target.value)}/></label><label className="mt-4 block text-xs text-neutral-300">Brush size <span className="float-right">{brushSize}px</span><input className="mt-2 w-full accent-blue-500" type="range" min="2" max="160" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/></label><div className="mt-6 grid gap-2"><button onClick={()=>apply(false)} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500">Remove Selected</button><button onClick={()=>apply(true)} className="rounded-xl bg-white/10 px-4 py-2.5 text-sm hover:bg-white/15">Restore Selected</button><button onClick={clear} className="rounded-xl px-4 py-2 text-sm text-neutral-400 hover:bg-white/5">Clear Selection</button></div><button onClick={download} className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium hover:bg-white/5"><Download size={16}/>Download PNG</button></aside>
    </main>
    <nav className="flex shrink-0 items-center justify-around border-t border-white/10 bg-neutral-950 p-2 md:hidden">{tools.slice(0,5).map(([id,label,Icon])=><button key={id} onClick={()=>setTool(id)} className={`flex flex-col items-center gap-1 rounded-lg px-3 py-2 text-[10px] ${tool===id?'text-blue-400':'text-neutral-400'}`}><Icon size={18}/>{label.split(' ')[0]}</button>)}</nav>
  </div>;
}
